apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
  labels:
    app: pagamento-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamento-service
  template:
    metadata:
      labels:
        app: pagamento-service
    spec:
      containers:
        - name: pagamento-service
          image: 637423657780.dkr.ecr.us-east-2.amazonaws.com/fiap-pagamento-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: pagamento-config
