apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-deployment
  labels:
    app: pedido-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedido-service
  template:
    metadata:
      labels:
        app: pedido-service
    spec:
      containers:
        - name: pedido-service
          image: 637423657780.dkr.ecr.us-east-2.amazonaws.com/fiap-pedido-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: pedido-config
